version: 2

models:
  - name: stg_dim_data
    columns: 
      - name: Data
        description: "{{doc('dim_data')}}"
        tests:
          - not_null
          - unique
      - name: Ano
        tests:
          - not_null
          - unique
      - name: Mes
        tests:
          - not_null
          - unique